part of 'app_pages.dart';
// DO NOT EDIT. This is code generated via package:get_cli/get_cli.dart

abstract class Routes {
  Routes._();
  static const HOME = _Paths.HOME;
  static const LOGIN = _Paths.LOGIN;
  static const SIGNUP = _Paths.SIGNUP;
  static const ONBOARDING = _Paths.ONBOARDING;
  static const SEARCH = _Paths.SEARCH;
  static const NOTIFICATIONS = _Paths.NOTIFICATIONS;
  static const CART = _Paths.CART;
  static const BILLS = _Paths.BILLS;
  static const MAIN_APP = _Paths.MAIN_APP;
  static const PROFILE = _Paths.PROFILE;
  static const SPLASH = _Paths.SPLASH;
  static const VERIFICATION = _Paths.VERIFICATION;
  static const CREATEPIN = _Paths.CREATEPIN;
  static const SUCCESS_ACCOUNT = _Paths.SUCCESS_ACCOUNT;
  static const FORGOT_PASSWORD = _Paths.FORGOT_PASSWORD;
  static const RESET_PASSWORD = _Paths.RESET_PASSWORD;
  static const EDIT_PROFILE = _Paths.EDIT_PROFILE;
  static const CONTACT = _Paths.CONTACT;
  static const DONATION = _Paths.DONATION;
  static const SHIPPING = _Paths.SHIPPING;
  static const MOBILE = _Paths.MOBILE;
  static const PAY_BILLS = _Paths.PAY_BILLS;
  static const HOT_DEALS = _Paths.HOT_DEALS;
  static const DEAL_DETAILS = _Paths.DEAL_DETAILS;
  static const ALL_MERCHANTS = _Paths.ALL_MERCHANTS;
  static const MERCHANT_DETAILS = _Paths.MERCHANT_DETAILS;
  static const GIFT = _Paths.GIFT;
  static const EXPENSE_TO_REWARD = _Paths.EXPENSE_TO_REWARD;
  static const TRANSACTIONS_EXTRACT = _Paths.TRANSACTIONS_EXTRACT;
  static const CREDIT = _Paths.CREDIT;
  static const COUPON = _Paths.COUPON;
  static const TEAMS = _Paths.TEAMS;
  static const REPORT = _Paths.REPORT;
  static const VENDOR_HOME = _Paths.VENDOR_HOME;
  static const VENDOR_ORDER = _Paths.VENDOR_ORDER;
  static const Q_R_SCANNER = _Paths.Q_R_SCANNER;
  static const DELIVERY_DRIVER = _Paths.DELIVERY_DRIVER;
  static const DELIVERY_ORDER_DETAILS = _Paths.DELIVERY_ORDER_DETAILS;
  static const VIPS_CLUB_HISTORY = _Paths.VIPS_CLUB_HISTORY;
  static const SETTINGS = _Paths.SETTINGS;
  static const CHECKOUT = _Paths.CHECKOUT;
  static const PROMOTIONS = _Paths.PROMOTIONS;
  static const PACKAGES = _Paths.PACKAGES;
  static const V_I_PS_CLUB = _Paths.V_I_PS_CLUB;
  static const SPIN_WHEEL = _Paths.SPIN_WHEEL;
}

abstract class _Paths {
  _Paths._();
  static const HOME = '/home';
  static const LOGIN = '/login';
  static const SIGNUP = '/signup';
  static const ONBOARDING = '/onboarding';
  static const SEARCH = '/search';
  static const NOTIFICATIONS = '/notifications';
  static const CART = '/cart';
  static const BILLS = '/bills';
  static const MAIN_APP = '/main-app';
  static const PROFILE = '/profile';
  static const SPLASH = '/splash';
  static const VERIFICATION = '/verification';
  static const CREATEPIN = '/createpin';
  static const SUCCESS_ACCOUNT = '/success-account';
  static const FORGOT_PASSWORD = '/forgot-password';
  static const RESET_PASSWORD = '/reset-password';
  static const EDIT_PROFILE = '/edit-profile';
  static const CONTACT = '/contact';
  static const DONATION = '/donation';
  static const SHIPPING = '/shipping';
  static const MOBILE = '/mobile';
  static const PAY_BILLS = '/pay-bills';
  static const HOT_DEALS = '/hot-deals';
  static const DEAL_DETAILS = '/deal-details';
  static const ALL_MERCHANTS = '/all-merchants';
  static const MERCHANT_DETAILS = '/merchant-details';
  static const GIFT = '/gift';
  static const EXPENSE_TO_REWARD = '/expense-to-reward';
  static const TRANSACTIONS_EXTRACT = '/transactions-extract';
  static const CREDIT = '/credit';
  static const COUPON = '/coupon';
  static const TEAMS = '/teams';
  static const REPORT = '/report';
  static const VENDOR_HOME = '/vendor-home';
  static const VENDOR_ORDER = '/vendor-order';
  static const Q_R_SCANNER = '/q-r-scanner';
  static const DELIVERY_DRIVER = '/delivery-driver';
  static const DELIVERY_ORDER_DETAILS = '/delivery-order-details';
  static const VIPS_CLUB_HISTORY = '/vips-club-history';
  static const SETTINGS = '/settings';
  static const CHECKOUT = '/checkout';
  static const PROMOTIONS = '/promotions';
  static const PACKAGES = '/packages';
  static const V_I_PS_CLUB = '/v-i-ps-club';
  static const SPIN_WHEEL = '/spin-wheel';
}
